### ISSUE TITLE
ModuleNotFoundError: No module named 'onnxgraphqt'

### ISSUE THREAD

**Issue by AlmogDeepKeep** [fateshelled/OnnxGraphQt#9]
I have successfully installed OnnxGraphQt on windows 11 and Ubuntu 22. In both cases, I get the following when I try to run the app as suggested in the readme
```
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\OneDrive\Documents\fix_onnx\OnnxGraphQt-main\onnxgraphqt\__main__.py", line 5, in <module>
    from onnxgraphqt.main_window import MainWindow
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'onnxgraphqt'
```
What am I doing wrong here?

**Comment by AlmogDeepKeep** [comment]
I removed all references to onnxgraphqt at the imports and it works

**Comment by fateshelled** [comment]
Thanks for pointing that out.
I forgot to update the README.md in the previous update.
README.md and some files have been fixed.

OnnxGraphQt can now be installed as a Python package, please install according to README.md.
